<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
	<StartupObject>nLogViewer.Tester.Program</StartupObject>
	<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Infrastructure\Convertors\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Config.Net" Version="5.1.5" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.0" />
    <PackageReference Include="NLog" Version="5.2.6" />
    <PackageReference Include="NLog.Extensions.Logging" Version="5.3.5" />
    <PackageReference Include="ProjectVersionInfoLib" Version="1.2.0" />
    <PackageReference Include="ProjectWPF.Styles" Version="1.0.0" />
  </ItemGroup>

  <ItemGroup>
    <None Update="nlog.config">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Infrastructure\Resources\Images\Medium\Debug.png" />
    <Resource Include="Infrastructure\Resources\Images\Medium\Error.png" />
    <Resource Include="Infrastructure\Resources\Images\Medium\Fatal.png" />
    <Resource Include="Infrastructure\Resources\Images\Medium\Info.png" />
    <Resource Include="Infrastructure\Resources\Images\Medium\Trace.png" />
    <Resource Include="Infrastructure\Resources\Images\Medium\Warning.png" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\nLogViewer\nLogViewer.csproj" />
  </ItemGroup>

</Project>
